name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build jar
        working-directory: ./task3
        run: mvn clean package
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build the docker image
        working-directory: ./task3
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: insolenset/task3:$(date +%s)
