name: Build Docker Image
on:
  push:
    branches:
      - task3
    paths:
      - task3/**

jobs:
  jar:
    name: build jar

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        working-directory: ./task3
        run: mvn -B package --file pom.xml

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: task3-jar
          path: task3/target/task3-0.0.1.jar

  docker:
    name: push docker image to docker hub

    runs-on: ubuntu-latest

    needs: jar

    steps:
      - uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: task3-jar
          path: task3/target/task3-0.0.1.jar

      - name: Set up timestamp tag
        id: tag
        run: |
          TIMESTAMP=$(date +%s)
          echo "TAG=insolenset/task3:$TIMESTAMP" >> $GITHUB_ENV

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build the docker image
        uses: docker/build-push-action@v3
        with:
          context: ./task3
          dockerfile: /Dockerfile
          push: true
          tags: ${{ env.TAG }}
